version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      time: '04:00'
      timezone: 'America/New_York'
    cooldown:
      default-days: 7
    open-pull-requests-limit: 3
    groups:
      production-dependencies:
        dependency-type: 'production'
        update-types:
          - 'patch'
          - 'minor'
      development-dependencies:
        dependency-type: 'development'
        update-types:
          - 'patch'
          - 'minor'
