on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches:
      - '**'
name: Push Event
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: npm
          cache-dependency-path: package.json
      - name: Upgrade npm
        run: npm install -g npm@latest
      - name: Install dependencies
        run: npm install
      - name: Eslint
        run: npm run lint
      # - name: Typecheck
      #   run: npm run typecheck
      - name: Audit
        run: npm audit --omit dev
      - name: Unit tests
        run: npm run test
      - name: Run build
        run: npm run build
